version: '3.5'

services:
  postgres:
    image: 'postgres'
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=ergomake
      - POSTGRES_USER=ergomake
      - POSTGRES_DB=ergomake
