apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-config
  namespace: '{{ .Values.elasticsearch.namespace }}'
  labels:
    app: filebeat-users
data:
  filebeat.yml: |
    filebeat.autodiscover:
     providers:
       - type: kubernetes
         node: ${NODE_NAME}
         hints.enabled: true
         hints.default_config:
           type: container
           paths:
             - /var/log/containers/*${data.kubernetes.container.id}.log
           fields_under_root: true
           fields:
             fields.id: "${data.kubernetes.annotations.preview.ergomake.dev/id}"
             fields.service: "${data.kubernetes.annotations.preview.ergomake.dev/service}"
             fields.owner: "${data.kubernetes.annotations.preview.ergomake.dev/owner}"
             fields.repo: "${data.kubernetes.annotations.preview.ergomake.dev/repo}"
             fields.sha: "${data.kubernetes.annotations.preview.ergomake.dev/sha}"

    output.elasticsearch:
      hosts: ["http://${ELASTICSEARCH_NAME}.${ELASTICSEARCH_NAMESPACE}.svc.cluster.local:9200"]
      username: "${ELASTICSEARCH_USERNAME}"
      password: "${ELASTICSEARCH_PASSWORD}"
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: filebeat
  namespace: '{{ .Values.elasticsearch.namespace }}'
  labels:
    app: filebeat-users
spec:
  selector:
    matchLabels:
      app: filebeat-users
  template:
    metadata:
      labels:
        app: filebeat-users
    spec:
      serviceAccountName: filebeat
      nodeSelector:
        preview.ergomake.dev/logs: 'true'
      tolerations:
        - key: preview.ergomake.dev/domain
          operator: Equal
          value: build
          effect: NoSchedule
        - key: preview.ergomake.dev/domain
          operator: Equal
          value: previews
          effect: NoSchedule
      containers:
        - name: filebeat
          image: 'docker.elastic.co/beats/filebeat:{{ .Values.elasticsearch.imageTag }}'
          imagePullPolicy: IfNotPresent
          args: ['-c', '/etc/filebeat.yml', '-e', '-strict.perms=false']
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: ELASTICSEARCH_NAME
              value: '{{ .Values.elasticsearch.nameOverride }}'
            - name: ELASTICSEARCH_NAMESPACE
              value: '{{ .Values.elasticsearch.namespace }}'
            - name: ELASTICSEARCH_USERNAME
              valueFrom:
                secretKeyRef:
                  name: elasticsearch-credentials
                  key: username
            - name: ELASTICSEARCH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: elasticsearch-credentials
                  key: password
          securityContext:
            runAsUser: 0
          volumeMounts:
            - name: config
              mountPath: /etc/filebeat.yml
              readOnly: true
              subPath: filebeat.yml
            - name: varlibdockercontainers
              mountPath: /var/lib/docker/containers
              readOnly: true
            - name: varlog
              mountPath: /var/log
              readOnly: true
          resources:
            limits:
              memory: 500Mi
      volumes:
        - name: config
          configMap:
            name: filebeat-config
            defaultMode: 0640
        - name: varlibdockercontainers
          hostPath:
            path: /var/lib/docker/containers
        - name: varlog
          hostPath:
            path: /var/log
        - name: data
          hostPath:
            path: /var/lib/filebeat-data
            type: DirectoryOrCreate
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: filebeat-nodes-reader
rules:
  - apiGroups: ['']
    resources: ['nodes', 'namespaces', 'pods']
    verbs: ['get', 'list', 'watch']
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: filebeat-nodes-reader
subjects:
  - kind: ServiceAccount
    name: filebeat
    namespace: '{{ .Values.elasticsearch.namespace }}'
roleRef:
  kind: ClusterRole
  name: filebeat-nodes-reader
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: filebeat
  namespace: '{{ .Values.elasticsearch.namespace }}'
