apiVersion: v1
kind: Service
metadata:
  name: front-service
  namespace: preview-core
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: front
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
